spring:
  application:
    name: "configserver"
  profile:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Peer-Vault/configurations"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true



server:
  port: 8071
  servlet:
    contextPath: "/config-server"


